<a href="https://colab.research.google.com/github/vladtsyp/study_datamining/blob/main/1_%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Практика Numpy

1. Скачайте этот блокнот к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература
- [**Блокнот с теорией**](https://clck.ru/35fwMP)
- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html


1) Импортировать numpy и написать версию

In [ ]:
import numpy as np
np.version.version

'1.23.5'

2) Создать нулевой вектор размера 10

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

3) Создать вектор заполненный 7-ами размера 7

In [ ]:
np.array([7]*7)

array([7, 7, 7, 7, 7, 7, 7])

In [ ]:
np.full(7, 7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
np.arange(10, 101, 2)

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
arr_5 = np.random.randn(5)
arr_5

array([-0.14726964,  0.67386738,  0.6175462 , -0.48575414, -0.35686517])

In [ ]:
arr_5[::-1]

array([-0.35686517, -0.48575414,  0.6175462 ,  0.67386738, -0.14726964])

In [ ]:
arr_5 = np.array([np.random.randint(0, 10) for x in range(5)])
arr_5

array([7, 6, 1, 2, 5])

In [ ]:
arr_5[::-1]

array([5, 2, 1, 6, 7])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
arr_6 = np.arange(9) # ???
arr_6 = arr_6.reshape(3, 3)
arr_6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
a = np.full((4, 4), 7)
np.fill_diagonal(a, [range(1, 5)])
a

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную числами от 0 до 4 в строках.

In [ ]:
np.array([[0, 1, 2, 3, 4] for x in range(5)])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
np.full((5, 5), [range(5)])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
arr_10 = np.random.random_sample((10, 10))
arr_10

array([[0.18588677, 0.1794146 , 0.35865354, 0.47024472, 0.61401803,
        0.58802359, 0.38565533, 0.31286169, 0.54447209, 0.38926512],
       [0.46099404, 0.47754221, 0.69579611, 0.39365438, 0.5439908 ,
        0.23484386, 0.83234597, 0.01818368, 0.48714335, 0.14342953],
       [0.51130727, 0.45542358, 0.47169285, 0.25528375, 0.22475046,
        0.77501362, 0.74685504, 0.6410744 , 0.8340889 , 0.64933248],
       [0.97547502, 0.17751343, 0.0624193 , 0.36331681, 0.90001498,
        0.49980799, 0.04900775, 0.74474134, 0.3585149 , 0.44033326],
       [0.8919896 , 0.07177132, 0.98286144, 0.53640016, 0.80894691,
        0.4427909 , 0.03694261, 0.67117222, 0.0914888 , 0.3780938 ],
       [0.01606099, 0.0554489 , 0.02196653, 0.3935357 , 0.9101098 ,
        0.00709687, 0.42906493, 0.39312432, 0.08228777, 0.54672196],
       [0.93030346, 0.17209491, 0.34326532, 0.74587154, 0.67163687,
        0.80357639, 0.34939904, 0.22334066, 0.52419913, 0.33056037],
       [0.13775596, 0.98578074, 0.6986583

In [ ]:
arr_10_m = arr_10.mean(axis=1, keepdims=True)
arr_10_m

array([[0.40284955],
       [0.42879239],
       [0.55648224],
       [0.45711448],
       [0.49124578],
       [0.28554178],
       [0.50942477],
       [0.51873953],
       [0.47435572],
       [0.39498773]])

In [ ]:
arr_10 - arr_10_m

array([[-0.21696277, -0.22343495, -0.04419601,  0.06739517,  0.21116848,
         0.18517404, -0.01719422, -0.08998786,  0.14162254, -0.01358443],
       [ 0.03220165,  0.04874982,  0.26700372, -0.03513802,  0.1151984 ,
        -0.19394853,  0.40355358, -0.41060871,  0.05835096, -0.28536287],
       [-0.04517497, -0.10105866, -0.08478938, -0.30119849, -0.33173177,
         0.21853138,  0.19037281,  0.08459217,  0.27760666,  0.09285025],
       [ 0.51836054, -0.27960105, -0.39469518, -0.09379767,  0.4429005 ,
         0.04269351, -0.40810672,  0.28762686, -0.09859958, -0.01678122],
       [ 0.40074382, -0.41947446,  0.49161567,  0.04515438,  0.31770113,
        -0.04845488, -0.45430317,  0.17992644, -0.39975697, -0.11315197],
       [-0.26948079, -0.23009288, -0.26357525,  0.10799393,  0.62456802,
        -0.27844491,  0.14352316,  0.10758254, -0.20325401,  0.26118018],
       [ 0.42087869, -0.33732986, -0.16615945,  0.23644677,  0.1622121 ,
         0.29415162, -0.16002572, -0.2860841 

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
arr_11 = np.random.random_sample((10, 10))
arr_11

array([[0.74829251, 0.05358667, 0.72990022, 0.80142739, 0.88679903,
        0.84474581, 0.60087456, 0.70395459, 0.72028489, 0.4318388 ],
       [0.38176717, 0.79859352, 0.97380879, 0.44750584, 0.34859731,
        0.98023088, 0.98135171, 0.14573372, 0.5233904 , 0.33343112],
       [0.51904858, 0.16627885, 0.41787167, 0.45335185, 0.24538955,
        0.67761965, 0.058339  , 0.85077879, 0.52497549, 0.44482387],
       [0.1558781 , 0.52867462, 0.08149003, 0.95025499, 0.47758548,
        0.08477143, 0.36585179, 0.67988647, 0.86414246, 0.48096846],
       [0.21703488, 0.5687875 , 0.45044793, 0.38101708, 0.16580822,
        0.1858512 , 0.09195669, 0.07812434, 0.40770154, 0.08678691],
       [0.22266251, 0.5224703 , 0.7803942 , 0.58837607, 0.67812956,
        0.67203863, 0.32439934, 0.36102442, 0.66000899, 0.70999175],
       [0.54683513, 0.03041067, 0.73038875, 0.75404764, 0.78209164,
        0.23435168, 0.47347379, 0.79245495, 0.83459955, 0.32663625],
       [0.34225925, 0.57049498, 0.6874707

In [ ]:
arr_11_m = np.median(arr_11, axis=0, keepdims=True)
arr_11_m

array([[0.36201321, 0.51181275, 0.58148791, 0.61937462, 0.48691439,
        0.45319516, 0.29508626, 0.69192053, 0.59249224, 0.43833133]])

In [ ]:
arr_11 - arr_11_m

array([[ 0.3862793 , -0.45822608,  0.14841231,  0.18205277,  0.39988464,
         0.39155065,  0.3057883 ,  0.01203406,  0.12779266, -0.00649254],
       [ 0.01975396,  0.28678077,  0.39232088, -0.17186878, -0.13831708,
         0.52703572,  0.68626545, -0.54618681, -0.06910183, -0.10490022],
       [ 0.15703538, -0.3455339 , -0.16361624, -0.16602278, -0.24152484,
         0.22442449, -0.23674726,  0.15885827, -0.06751675,  0.00649254],
       [-0.20613511,  0.01686187, -0.49999788,  0.33088037, -0.00932891,
        -0.36842372,  0.07076553, -0.01203406,  0.27165022,  0.04263713],
       [-0.14497833,  0.05697476, -0.13103998, -0.23835754, -0.32110617,
        -0.26734396, -0.20312957, -0.61379619, -0.18479069, -0.35154442],
       [-0.1393507 ,  0.01065755,  0.19890629, -0.03099855,  0.19121517,
         0.21884347,  0.02931308, -0.33089611,  0.06751675,  0.27166041],
       [ 0.18482192, -0.48140207,  0.14890084,  0.13467302,  0.29517725,
        -0.21884347,  0.17838753,  0.10053442

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбцы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
arr_12 = np.random.random_sample((5, 5))
arr_12

array([[0.23649728, 0.85695793, 0.21976859, 0.15518578, 0.11206236],
       [0.53989914, 0.36641652, 0.31811947, 0.0258579 , 0.76330144],
       [0.91873065, 0.03042831, 0.07109535, 0.94241487, 0.17944837],
       [0.00279229, 0.36405067, 0.29450464, 0.9480603 , 0.29787291],
       [0.21749258, 0.94268502, 0.81152694, 0.61946166, 0.24962568]])

In [ ]:
np.hstack((np.hstack((arr_12, arr_12.max(axis=1, keepdims=True))), arr_12.min(axis=1, keepdims=True)))

array([[0.23649728, 0.85695793, 0.21976859, 0.15518578, 0.11206236,
        0.85695793, 0.11206236],
       [0.53989914, 0.36641652, 0.31811947, 0.0258579 , 0.76330144,
        0.76330144, 0.0258579 ],
       [0.91873065, 0.03042831, 0.07109535, 0.94241487, 0.17944837,
        0.94241487, 0.03042831],
       [0.00279229, 0.36405067, 0.29450464, 0.9480603 , 0.29787291,
        0.9480603 , 0.00279229],
       [0.21749258, 0.94268502, 0.81152694, 0.61946166, 0.24962568,
        0.94268502, 0.21749258]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрицы. Найти произведение этих матриц. Найти обратную матрицу этого произведения.  

In [ ]:
arr_13 = np.arange(1, 51) # 51 не включая??
arr_13

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
# нечетные
arr_13_1 = arr_13[::2]
arr_13_1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [ ]:
# четные
arr_13_2 = arr_13[arr_13 % 2 == 0]
arr_13_2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [ ]:
arr_13_1.shape, arr_13_2.shape

((25,), (25,))

In [ ]:
arr_13_1 = arr_13_1.reshape(5, 5)
arr_13_2 = arr_13_2.reshape(5, 5)
print(arr_13_1, '\n\n', arr_13_2)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]] 

 [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]


In [ ]:
# произведение матриц
arr_13_f = np.dot(arr_13_1, arr_13_2)
arr_13_f

array([[ 750,  800,  850,  900,  950],
       [1850, 2000, 2150, 2300, 2450],
       [2950, 3200, 3450, 3700, 3950],
       [4050, 4400, 4750, 5100, 5450],
       [5150, 5600, 6050, 6500, 6950]])

In [ ]:
# обратная матрица этого произведения
np.linalg.inv(arr_13_f)

LinAlgError: ignored

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
# первый вариант
arr_14 = np.array([[0, 1]*4, [1, 0]*4]*4)
arr_14

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
# второй вариант
arr_14 = np.zeros((8, 8), dtype=int)
arr_14[1::2, ::2] = 1
arr_14[::2, 1::2] = 1
arr_14

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
# третий вариант
np.tile(np.array([[0, 1], [1, 0]]), (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])